text = input("Enter a string to test:")

print("RESULTS")

print("find('a'):", text.find("a"))
print("count('a'):", text.count("a"))
print("startswith('A'):", text.startswith("A"))
print("endswith('.'):", text.endswith("."))

print("isalnum():", text.isalnum())
print("isalpha():", text.isalpha())
print("isdigit():", text.isdigit())
print("isnumeric():", text.isnumeric())

print("islower():", text.islower())
print("isupper():", text.isupper())
print("istitle():", text.istitle())

print("isspace():", text.isspace())
print("isprintable():", text.isprintable())
print("isascii():", text.isascii())
print("isidentifier():", text.isidentifier())
print("center(20, '*'):", text.center(20, "*"))
print("ljust(20, '-'): ", text.ljust(20, "-"))
print("rjust(20, '+'):", text.rjust(20, "+"))
print("zfill(20):", text.zfill(20))
print("rfind('a'):", text.rfind("a"))
print("rindex('a'):", text.rindex("a"))
print("partition(' '):", text.partition(" "))
print("rpartition(' '):", text.rpartition(" "))
print("format():", "Hello, {}!".format(text))
print("format_map():", "Hello, {name}!".format_map({"name": text}))
print("splitlines():", text.splitlines())
print("rsplit(','):", text.rsplit(","))
print("expandtabs(3):", text.expandtabs(3))